"use client";
import { useState, useCallback } from "react";
import Layout from "../../components/Layout";
import { supabase } from "../../lib/supabase";

type AttendanceRow = {
  date: string;
  entry_time: string | null;
  is_late: boolean;
  employees: { name: string; role: string } | null;
};

type EmployeeSummary = {
  name: string;
  role: string;
  totalDays: number;
  presentDays: number;
  lateDays: number;
  absentDays: number;
};

function buildSummary(rows: AttendanceRow[], from: string, to: string): EmployeeSummary[] {
  // Count working days in range
  const workingDays: string[] = [];
  const d = new Date(from);
  const end = new Date(to);
  while (d <= end) {
    if (d.getDay() !== 0 && d.getDay() !== 6) {
      workingDays.push(d.toISOString().slice(0, 10));
    }
    d.setDate(d.getDate() + 1);
  }

  const map = new Map<string, EmployeeSummary>();
  for (const row of rows) {
    const name = row.employees?.name ?? "Unknown";
    if (!map.has(name)) {
      map.set(name, { name, role: row.employees?.role ?? "", totalDays: workingDays.length, presentDays: 0, lateDays: 0, absentDays: 0 });
    }
    const s = map.get(name)!;
    if (row.entry_time) s.presentDays++;
    if (row.is_late) s.lateDays++;
  }

  // Calculate absences
  const all = Array.from(map.values());
  all.forEach((s) => { s.absentDays = Math.max(0, s.totalDays - s.presentDays); });
  return all.sort((a, b) => (b.lateDays + b.absentDays) - (a.lateDays + a.absentDays));
}

export default function ReportsPage() {
  const now = new Date();
  const firstOfMonth = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10);
  const [from, setFrom] = useState(firstOfMonth);
  const [to, setTo] = useState(now.toISOString().slice(0, 10));
  const [summary, setSummary] = useState<EmployeeSummary[]>([]);
  const [loading, setLoading] = useState(false);
  const [searched, setSearched] = useState(false);
  const [sendMsg, setSendMsg] = useState("");
  const [sending, setSending] = useState(false);

  const runSearch = useCallback(async () => {
    setLoading(true);
    setSearched(true);
    const { data } = await supabase()
      .from("attendance")
      .select("date, entry_time, is_late, employees(name, role)")
      .gte("date", from)
      .lte("date", to);
    setSummary(buildSummary((data as AttendanceRow[]) ?? [], from, to));
    setLoading(false);
  }, [from, to]);

  async function sendReport() {
    setSending(true);
    setSendMsg("");
    try {
      const db = supabase();
      const { data: settings } = await db
        .from("settings")
        .select("smtp_user, smtp_pass, report_email")
        .single();

      if (!settings?.smtp_user || !settings?.smtp_pass || !settings?.report_email) {
        setSendMsg("Configure Gmail SMTP credentials in Settings first.");
        return;
      }

      const irregular = summary.filter((s) => s.lateDays > 0 || s.absentDays > 0);
      const html = `
        <h2 style="font-family:sans-serif">Attendance Report: ${from} to ${to}</h2>
        <table border="1" cellpadding="6" style="border-collapse:collapse;font-family:sans-serif">
          <tr><th>Employee</th><th>Role</th><th>Present</th><th>Late</th><th>Absent</th></tr>
          ${irregular.map((s) => `<tr>
            <td>${s.name}</td><td>${s.role}</td>
            <td>${s.presentDays}/${s.totalDays}</td>
            <td style="color:${s.lateDays > 0 ? "#b45309" : "inherit"}">${s.lateDays}</td>
            <td style="color:${s.absentDays > 0 ? "#dc2626" : "inherit"}">${s.absentDays}</td>
          </tr>`).join("")}
        </table>
        <p style="font-family:sans-serif;color:#6b7280">Generated by Mark-it</p>
      `;

      const res = await fetch("/api/send-report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          smtp_user: settings.smtp_user,
          smtp_pass: settings.smtp_pass,
          recipients: settings.report_email,
          subject: `Attendance Report: ${from} to ${to}`,
          html_body: html,
        }),
      });

      setSendMsg(res.ok ? "Report sent successfully!" : "Failed to send report.");
    } catch {
      setSendMsg("Failed to send report.");
    } finally {
      setSending(false);
    }
  }

  const flagged = summary.filter((s) => s.lateDays > 0 || s.absentDays > 0);

  return (
    <Layout>
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">Reports</h1>
          <p className="mt-1 text-sm text-slate-400">Attendance summary and irregular employee report</p>
        </div>
        {searched && summary.length > 0 && (
          <button className="btn-primary" onClick={sendReport} disabled={sending}>
            {sending ? "Sending…" : "Email Report"}
          </button>
        )}
      </div>

      {/* Date range */}
      <div className="card mb-6">
        <div className="grid gap-4 sm:grid-cols-3">
          <div>
            <label className="label">From</label>
            <input className="input" type="date" value={from} onChange={(e) => setFrom(e.target.value)} />
          </div>
          <div>
            <label className="label">To</label>
            <input className="input" type="date" value={to} onChange={(e) => setTo(e.target.value)} />
          </div>
          <div className="flex items-end">
            <button className="btn-primary w-full" onClick={runSearch} disabled={loading}>
              {loading ? "Loading…" : "Generate Report"}
            </button>
          </div>
        </div>
        {/* Quick range buttons */}
        <div className="mt-4 flex gap-2">
          {[
            { label: "This Week", days: 7 },
            { label: "This Month", days: 30 },
            { label: "Last 3 Months", days: 90 },
          ].map(({ label, days }) => (
            <button
              key={label}
              onClick={() => {
                const end = new Date();
                const start = new Date();
                start.setDate(start.getDate() - days);
                setFrom(start.toISOString().slice(0, 10));
                setTo(end.toISOString().slice(0, 10));
              }}
              className="rounded-lg border border-slate-700 px-3 py-1.5 text-xs text-slate-400 hover:border-indigo-500 hover:text-white transition-colors"
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      {sendMsg && (
        <p className={`mb-6 rounded-lg px-4 py-3 text-sm ${sendMsg.includes("successfully") ? "bg-emerald-900/30 text-emerald-300" : "bg-red-900/30 text-red-300"}`}>
          {sendMsg}
        </p>
      )}

      {!searched ? (
        <div className="card flex flex-col items-center py-16 text-center">
          <p className="text-slate-500">Select a date range and click Generate Report</p>
        </div>
      ) : summary.length === 0 ? (
        <div className="card py-16 text-center">
          <p className="text-slate-400">No attendance data for this period.</p>
        </div>
      ) : (
        <>
          {/* Summary cards */}
          <div className="mb-6 grid grid-cols-3 gap-4">
            <div className="card-sm text-center">
              <div className="text-2xl font-bold text-slate-200">{summary.length}</div>
              <div className="text-xs text-slate-500">Employees tracked</div>
            </div>
            <div className="card-sm text-center">
              <div className="text-2xl font-bold text-amber-400">{flagged.filter((s) => s.lateDays > 0).length}</div>
              <div className="text-xs text-slate-500">Had late arrivals</div>
            </div>
            <div className="card-sm text-center">
              <div className="text-2xl font-bold text-red-400">{flagged.filter((s) => s.absentDays > 0).length}</div>
              <div className="text-xs text-slate-500">Had absences</div>
            </div>
          </div>

          {/* Full table */}
          <div className="card overflow-hidden p-0">
            <div className="border-b border-slate-800 px-6 py-4">
              <h2 className="font-semibold text-white">Employee Summary</h2>
            </div>
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-800">
                  {["Employee", "Role", "Present", "Late", "Absent", "Attendance Rate"].map((h) => (
                    <th key={h} className="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-400">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {summary.map((s) => {
                  const rate = s.totalDays > 0 ? Math.round((s.presentDays / s.totalDays) * 100) : 0;
                  return (
                    <tr key={s.name} className="hover:bg-slate-800/40 transition-colors">
                      <td className="px-5 py-3.5 font-medium text-white">{s.name}</td>
                      <td className="px-5 py-3.5 text-slate-400">{s.role}</td>
                      <td className="px-5 py-3.5 text-slate-300">{s.presentDays} / {s.totalDays}</td>
                      <td className="px-5 py-3.5">
                        {s.lateDays > 0
                          ? <span className="badge-yellow">{s.lateDays} day{s.lateDays !== 1 ? "s" : ""}</span>
                          : <span className="text-slate-500">—</span>}
                      </td>
                      <td className="px-5 py-3.5">
                        {s.absentDays > 0
                          ? <span className="badge-red">{s.absentDays} day{s.absentDays !== 1 ? "s" : ""}</span>
                          : <span className="text-slate-500">—</span>}
                      </td>
                      <td className="px-5 py-3.5">
                        <div className="flex items-center gap-2">
                          <div className="h-1.5 w-20 rounded-full bg-slate-700">
                            <div
                              className={`h-1.5 rounded-full ${rate >= 90 ? "bg-emerald-500" : rate >= 70 ? "bg-amber-500" : "bg-red-500"}`}
                              style={{ width: `${rate}%` }}
                            />
                          </div>
                          <span className="text-slate-400">{rate}%</span>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </>
      )}
    </Layout>
  );
}
